# Generated by Django 3.0.5 on 2020-05-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('summary', models.TextField()),
                ('featured_photos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('pan_vat_number', models.IntegerField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('user_type', models.IntegerField()),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserGymRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.User')),
            ],
        ),
        migrations.AddField(
            model_name='gym',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.User'),
        ),
    ]
