# Generated by Django 3.0.5 on 2020-05-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_auto_20200509_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pan_vat_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
