# Generated by Django 3.0.5 on 2020-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_complete',
            field=models.IntegerField(default=0),
        ),
    ]
