# Generated by Django 3.0.5 on 2020-06-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_auto_20200526_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='featured_photos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
